version: 2.1

jobs:
  checkout_and_test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
#      - restore_cache:
#          keys:
#            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
#            - v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
#            - v2-npm-deps-{{ .Branch }}
#            - v2-npm-deps-
      - run:
          name: install NPM dependencies
          command: npm install
#      - save_cache:
#          key: v2-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
#          paths:
#            - node_modules
      - run:
          name: test
          command: npm run cover
      - when:
          condition:
            equal: [ "16.10", << parameters.node-version >> ]
          steps:
            - run:
                name: upload coverage report
                command: npx codecov
            - save_cache:
                key: v1-source-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                  - "~"
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - restore_cache:
          key: v1-source-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - run:
          name: Add github to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: do a release
          command: npx semantic-release

workflows:
  version: 2
  build_and_publish:
    jobs:
      - checkout_and_test:
          matrix:
            parameters:
              node-version: ["12.22", "14.18", "16.10"]
      - publish:
          requires:
            - checkout_and_test
          filters:
            branches:
              only:
                - master
